name: Close PR

on:
  pull_request:
    types: [closed]

env:
  PR_NUMBER: ${{ github.event.number }}
  AWS_BUCKET_NAME: gatsby-uswds-ts-starter
  AWS_REGION: us-west-1

jobs:
  remove-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Write AWS_REGION to env context
        run: |
          echo "AWS_REGION=$(echo $AWS_REGION)" >> $GITHUB_ENV
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Remove staging build folder
        run: aws s3 rm s3://$AWS_BUCKET_NAME/ --exclude "*" --include "$(echo $PR_NUMBER)-*" --recursive