name: Deploy Production

on:
  push:
    branches: [main]

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  run-ci:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Lint, test, build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check types
        run: pnpm type-check

      - name: Check linting
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v5

      - name: Set DESTINATION_FOLDER for branch
        run: |
          echo "DESTINATION_FOLDER=main" >> $GITHUB_ENV

      - name: Build project
        run: pnpm build
        env: 
          SITE_URL: "${{ secrets.STAGE_SITE_URL }}"
          DEPLOY_PREFIX: "/${{env.DESTINATION_FOLDER}}/"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Deploy to AWS
        run: aws s3 sync ./public/ s3://gatsby-uswds-ts-starter/${{env.DESTINATION_FOLDER}} --acl public-read --delete
      
      - name: Update PR with staging URL
        uses: mshick/add-pr-comment@v1
        with:
          # Deploy to S3 for the staging URL
          message: |
            **🚢  Here is the frontend staging link: 🚢**   
            Find it here: http://gatsby-uswds-ts-starter.s3-website-us-west-1.amazonaws.com/${{env.DESTINATION_FOLDER}} !
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]" # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
